name: Feature Request
description: Suggest a new feature
title: "[FEATURE] "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: Thanks for suggesting an improvement!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature
      placeholder: What would you like to add?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this be implemented?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Other approaches considered
